language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository --yes ppa:tobydox/mingw
  - sudo apt-get update -qq
  - sudo apt-get -qq install mingw32-x-gcc mingw32-x-binutils wine

before_script:
  - cp travis/Toolchain-mingw32.cmake ~/

script:
  - make test CC=i686-w64-mingw32-g++ CXX=i686-w64-mingw32-g++ WINDRES=i686-w64-mingw32-windres DLLTOOL=i686-w64-mingw32-dlltool AR=i686-w64-mingw32-ar CMAKEFLAGS='-DCMAKE_TOOLCHAIN_FILE=~/Toolchain-mingw32.cmake'
  - cd test && wine ./test
