dist: xenial
sudo: false

language: cpp

addons:
  apt:
    packages:
    - gcc-mingw-w64-i686
    - g++-mingw-w64-i686
    - binutils-mingw-w64-i686
    - wine1.4

script:
  - cmake --version
  - i686-w64-mingw32-gcc --version
  - i686-w64-mingw32-g++ --version
  - mkdir build && cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-mingw32.cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j4 VERBOSE=1
  - cd test && wine ./STEP_mid.test.exe
