language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository --yes ppa:tobydox/mingw
  - sudo apt-get update -qq
  - sudo apt-get -qq install mingw32-x-gcc
  - sudo apt-get -qq install mingw32-x-binutils
  - sudo apt-get -qq install wine

install:
  - export PATH=${PATH}:/opt/mingw32/bin
  - make test CC=i686-w64-mingw32-g++ CXX=i686-w64-mingw32-g++ WINDRES=i686-w64-mingw32-windres DLLTOOL=i686-w64-mingw32-dlltool AR=i686-w64-mingw32-ar CMAKEFLAGS='-DCMAKE_C_COMPILER=i686-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=i686-w64-mingw32-g++ -DCMAKE_SHARED_LIBRARY_LINK_C_FLAGS="" -DCMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS=""'

script:
  - cd test
  - wine ./test

notifications:
  email:
    recipients:
      - ntjapanize@yahoo.co.jp
