dist: trusty
sudo: false

language: cpp

compiler:
  - gcc

addons:
  apt:
    packages:
    - gcc-mingw-w64
    - wine

script:
  - mkdir build && cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-mingw32.cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j4 VERBOSE=1
  - cd test && wine ./STEP_mid.test.exe
