language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository --yes ppa:tobydox/mingw-x-precise
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install -qq mingw32-x-binutils mingw32-x-gcc wine cmake

before_script:
  - cp travis/Toolchain-mingw32.cmake ~/
  - export PATH=${PATH}:/opt/mingw32/bin

script:
  - mkdir build && cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=~/Toolchain-mingw32.cmake ..
  - make -j4
  - cd test && wine ./STEP_mid.test.exe
