cache:
  - c:\msys64\var\cache\pacman\pkg

install:
  - git submodule update --init --recursive
  - '%APPVEYOR_BUILD_FOLDER%\appveyor\install.bat'

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\appveyor\build.bat'
