build: off

cache:
  - c:\msys64\var\cache\pacman\pkg
  - c:\msys64\var\lib\pacman\sync

install:
  - git submodule update --init --recursive
  - '%APPVEYOR_BUILD_FOLDER%\appveyor\install.bat'

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\appveyor\build.bat'

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\appveyor\test.bat'
