name: Build and test

on: [push]

defaults:
  run:
    shell: msys2 {0}

jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            mingw-w64-i686-gcc
            mingw-w64-x86_64-gcc
            mingw-w64-i686-make
            mingw-w64-x86_64-make
            mingw-w64-i686-cmake
            mingw-w64-x86_64-cmake
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: ./build_msys.sh
      - name: Test
        run: ./test_all.sh
