name: Build and test

on: [push]

jobs:
  build_and_test:
    strategy:
      matrix:
        target: [STEP_K, STEP_M]
        arch: [i686, x86_64]
        exclude:
          - target: STEP_M
            arch: x86_64
        include:
          - arch: i686
            msystem: MINGW32
          - arch: x86_64
            msystem: MINGW64
    defaults:
      run:
        shell: msys2 {0}
    runs-on: windows-latest
    env:
      TARGET: ${{ matrix.target }}
      BUILD_DIR: build
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: false
          install: >-
            git
            make
            mingw-w64-${{ matrix.arch }}-gcc
            mingw-w64-${{ matrix.arch }}-cmake
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Configure
        run: |
          mkdir ${BUILD_DIR} && cd ${BUILD_DIR}
          cmake -G "MSYS Makefiles" -D${TARGET}=1 ..
      - name: Build
        run: |
          cd ${BUILD_DIR}
          cmake --build .
      - name: Test
        run: |
          cd ${BUILD_DIR}
          ctest
